# Windows: link the C runtime statically so omuse.exe runs without the Visual
# C++ Redistributable, as Zed does for GPUI. Other targets are unaffected.
[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static"]
